### ISSUE TITLE
centos上编译报错了

### ISSUE THREAD

**Issue by amhoho** [Albert-Zhan/php-decrypt#1]
In file included from /php-decrypt/decrypt.c:30:0:
/php-decrypt/lib.h:29:15: warning: missing terminating " character [enabled by default]
 #   define DS "\"
/php-decrypt/decrypt.c: In function ‘decrypt_compile_file’:
/php-decrypt/decrypt.c:57:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
             for(int i=0;i<=size;i++)
/php-decrypt/decrypt.c:57:13: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [decrypt.lo] Error 1

**Comment by Albert-Zhan** [comment]
已修复
