### ISSUE TITLE
您好，询问一下能否解密sg11加密

### ISSUE THREAD

**Issue by JiangQinZhe** [Albert-Zhan/php-decrypt#2]
您好，询问一下能否解密sg11加密（sourceguardian）

**Comment by Albert-Zhan** [comment]
> 您好，询问一下能否解密sg11加密（sourceguardian）

sg11是使用解密扩展进行解密运行加密代码的，理论是可以被解密的。

**Comment by JiangQinZhe** [comment]
您这边如果有空闲时间，能否帮我尝试一下，我目前暂时没有空闲的服务器。
加密文件链接：https://www.lanzous.com/ib61pkd

**Comment by JiangQinZhe** [comment]
无法使用？怎么回事？

**Comment by Albert-Zhan** [comment]
> 无法使用？怎么回事？
编译错误请贴出代码，使用问题请仔细看说明

**Comment by JiangQinZhe** [comment]
居然秒回，国人素质还是高。
您稍等，我贴出原因

**Comment by JiangQinZhe** [comment]
配置环境：Centos7+Nginx1.16.1+宝塔面板+php7.1.29
问题：先加载解密扩展，后加载加密扩展，访问被加密后的文件，保存的decrypt.code中还是原加密文件，无扩展加密（eval变种加密一样无法解密）

**Comment by Albert-Zhan** [comment]
> 配置环境：Centos7+Nginx1.16.1+宝塔面板+php7.1.29
> 
> 问题：先加载解密扩展，后加载加密扩展，访问被加密后的文件，保存的decrypt.code中还是原加密文件，无扩展加密（eval变种加密一样无法解密）

可能得原因是sg11解密扩展做判断了(目前流行的加密扩展都一样)，并没有把解密后的代码返回给我们的扩展上，而是等后面返回给php解释引擎。

**Comment by laikee99** [comment]
> > 配置环境：Centos7+Nginx1.16.1+宝塔面板+php7.1.29
> > 问题：先加载解密扩展，后加载加密扩展，访问被加密后的文件，保存的decrypt.code中还是原加密文件，无扩展加密（eval变种加密一样无法解密）
> 
> 可能得原因是sg11解密扩展做判断了(目前流行的加密扩展都一样)，并没有把解密后的代码返回给我们的扩展上，而是等后面返回给php解释引擎。

那这种情况大佬可以提供一点绕过的思路吗？
