### ISSUE TITLE
你好，我们现有的通达oa是运行在5.4的环境上面的

### ISSUE THREAD

**Issue by Ghaker** [Albert-Zhan/php-decrypt#3]
我并没有看到readme中有windows版本的下载链接，而且我看到，点c文件中的代码量很少。
所以有一点怀疑态度

**Comment by Ghaker** [comment]
如果可以的话用邮箱交流
suminghk@163.com
github我这边需要翻墙才能正常使用

**Comment by Albert-Zhan** [comment]
> 我并没有看到readme中有windows版本的下载链接，而且我看到，点c文件中的代码量很少。
> 所以有一点怀疑态度

其实真正实现的代码就下面这段：
`zend_op_array *decrypt_compile_file(zend_file_handle *file_handle, int type)
{
    if(is_dirs(DCG(global_new)))
    {
        php_error_docref(NULL,E_ERROR,"%s folder does not exist",DCG(global_new));
    }
    char *buf;
    size_t size;
    if(zend_stream_fixup(file_handle,&buf,&size)==SUCCESS)
    {
        char *dir_name=strcat(DCG(global_new),DS);
        char *file_name= "decrypt.code";
        FILE *fp = NULL;
        fp=fopen(strcat(dir_name,file_name),"a+");
        if(fp!=NULL)
        {
            fprintf(fp,"%s",file_handle->filename);
            fprintf(fp,"%s",BR);
            int i;
            for(i=0;i<=size;i++)
            {
                fprintf(fp,"%c",buf[i]);
            }
            fprintf(fp,"%s",BR);
        }
        fclose(fp);
    }
    return old_compile_file(file_handle,type);
}`
扩展初始化钩住php引擎执行时的钩子，php引擎就会执行钩子上的扩展，加密扩展实现原理也跟这个一样

**Comment by Albert-Zhan** [comment]
> 如果可以的话用邮箱交流
> [suminghk@163.com](mailto:suminghk@163.com)
> github我这边需要翻墙才能正常使用

还有我这里是不保证你能解密成功的，后面我会修改readme的

**Comment by Ghaker** [comment]
thanks
